export { addNotesToStorage } from 'helpers/addNotesToStorage/addNotesToStorage'
export { getAllNotesData, getSingleNote } from 'helpers/getNotesData/getNotesData'
export { deleteNote } from 'helpers/deleteNote/deleteNote'
export { getDeletedNotes } from 'helpers/deleteNote/getDeletedNotes'
export { archiveNotes } from 'helpers/archiveNotes/archiveNotes'
export { getArchivedNotes } from 'helpers/archiveNotes/getArchivedNotes'