export { Home } from 'pages/home/Home'
export { Dashboard } from 'pages/dashboard/Dashboard'
export { Login } from 'pages/login/Login'
export { Label } from 'pages/label/Label'
export { Archive } from 'pages/archive/Archive'
export { Trash } from 'pages/trash/Trash'